unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set-option -g mouse on
set -g default-command /usr/bin/zsh
#set-option -g status-position top 
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'catppuccin/tmux'
#set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin 'dracula/tmux'
# ...alongside
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'
# set -g @catppuccin_flavour 'mocha' # latte,frappe, macchiato or mocha
# set -g @catppuccin_window_separator ""
# set -g @catppuccin_window_left_separator ""
# set -g @catppuccin_window_middle_separator "█"
# set -g @catppuccin_window_right_separator ""
#set -g @theme_variation "night"
#set -g @theme_transparent_status_bar 'true'
# available plugins: battery, cpu-usage, git, gpu-usage, ram-usage, tmux-ram-usage, network, network-bandwidth, network-ping, ssh-session, attached-clients, network-vpn, weather, time, mpc, spotify-tui, krbtgt, playerctl, kubernetes-context, synchronize-panes
set -g @dracula-plugins "cpu-usage time ram-usage attached-clients"

set -g @dracula-show-powerline true
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
