import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
  #"~/.config/alacritty/dracula.toml"
]
[window]
title="alacritty"
dynamic_title=false
#opacity=0.8
#startup_mode="Maximized"
[window.dimensions]
columns=113
lines=23
#[window.position]
#x=210
#y=85
[window.padding]
x=3
y=3
[cursor.style]
shape="beam"
blinking="Never"

[font]
size=13
[font.normal]
family="CaskaydiaCove Nerd Font"
style="Regular"

