dunst &
picom -b &
sxhkd &
feh --bg-fill --no-fehbg ~/wallpapers/tress.png &
greenclip daemon &
xautolock -time 10  -locker "i3lock -i $HOME/.config/xautolock/lockscreen.png" &
dbus-update-activation-environment DISPLAY &
exec i3 
