dunst &
picom -b &
sxhkd &
nm-applet &
blueman-applet &
xgamma -gamma 0.7 &
#wallpaper random &
~/.cache/wall &
xrdb -merge .Xresources &
greenclip daemon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xautolock -time 10  -locker "slock" &
dbus-update-activation-environment DISPLAY &
exec qtile start 
#exec i3
