[mgr]
ratio = [1,4,3]
#show_hidden=true
[preview]
image_quality = 60

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" }
]

pdf = [
{ run = 'zen-browser "$@"',orphan = true , for = "unix" }
]

image = [
{run = 'sxiv -b "$@"' , orphan=true,for="unix"}
]

video = [
{run = 'mpv "$@"',orphan=true,for="unix"}
]

audio = [
  { run = 'music-player "$@"',orphan=true,for="unix"}
]

librefiles = [
{run = 'libreoffice "$@"',orphan=true,for="unix"}
]

[open]
rules = [
{name = "*.pdf",use="pdf"},
{mime = "text/*", use="edit"},
{mime = "image/*",use="image"},
{mime = "video/*",use = "video"},
{mime = "audio/*",use = "audio"},
{name = "*.odt",use = "librefiles"},
{ mime = "application/{json,x-ndjson}", use = "edit" },
{name = "*" , use = "edit"}
]
