[global/wm]
include-file=~/.config/polybar/tokyonight.ini

margin-bottom = 0
margin-top = 0
[bar/own]
width = 100%
height = 20pt
tray-detached = true
background = ${colors.background}
foreground = ${colors.foreground}
separator = " "
font-0 = CaskaydiaCove Nerd Font ;2

modules-left = arch-label xworkspaces
modules-right = memory storage battery pulseaudio backlight date  ambient-music network systray poweroff 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
[module/arch-label]
type = custom/script
label=%output%
exec = echo "   "
click-left = $TERMINAL $HOME/.config/polybar/scripts/sysinfo.sh
label-foreground = ${colors.foreground}
label-background = ${colors.foreground-alt}

[module/systray]
type = internal/tray
format-margin = 8pt
tray-spacing = 8pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.foreground-alt}
label-active-underline= ${colors.foreground}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.red}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.foreground}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
label-maxlen = 15

[module/pulseaudio]
type = internal/pulseaudio

label-volume = "  %percentage%% " 
label-volume-background = ${colors.foreground-alt}
#label-volume-underline = ${colors.blue}
use-ui-max = true
label-muted = " 󰝟 %percentage%% "
label-muted-foreground = ${colors.red}
label-muted-background = ${colors.foreground-alt}

[module/memory]
type = internal/memory
interval = 2
label = " 󰍛 %gb_free%/%gb_total% "
label-background = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 1
date= %d-%m-%Y %a | 󱑆 %H:%M
label = " %date% "
label-background = ${colors.foreground-alt}

[module/backlight]
type = internal/backlight
card = amdgpu_bl1
use-actual-brightness = true
poll-interval = 0
label = " 󰃠 %percentage%% "
label-background = ${colors.foreground-alt}

[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
poll-interval = 5
label-full = " 󰁹 %percentage%% "
label-low = " 󰁹 %percentage%% "
label-charging = " 󰁹 %percentage%% "
label-discharging = " 󰁹 %percentage%% "
label-charging-background = ${colors.foreground-alt}
label-charging-foreground = ${colors.foreground}
label-discharging-foreground = ${colors.red}
label-discharging-background = ${colors.foreground-alt}
label-full-background = ${colors.foreground-alt}
label-low-background = ${colors.foreground-alt}

[module/storage]
type = custom/script
interval = 50
label = %output%
exec = echo "  /home $(df -h | grep -vE '^Filesystem|tmpfs|run|dev$'| grep "^/dev/sda3" | awk '{print $4" / "$2}') "
label-background= ${colors.foreground-alt}

[module/poweroff]
type = custom/script
label = %output%
tail = true
exec = echo "  ⏻  "
click-left = $HOME/.config/polybar/scripts/poweroff.sh
label-background = ${colors.foreground-alt}
label-foreground = ${colors.foreground}

[module/ambient-music]
type = custom/script
label = %output%
tail = true
exec = echo " 󰎆 "
click-left = $HOME/.config/polybar/scripts/ambient-sounds.sh
label-foreground = ${colors.foreground}

[module/wireless-network]
type = internal/network
interface = wlan0

[module/network]
type = internal/network
interface = wlan0
accumulate-stats = true
interface-type = wireless
interval = 3.0
format-connected = %{A1:$TERMINAL nmtui:}<ramp-signal> %{A}
format-disconnected = %{A1:$TERMINAL nmtui:}<label-disconnected> %{A}
label-disconnected = 󰤮
label-connected-foreground = ${colors.foreground}
label-disconnected-foreground = ${colors.foreground}
ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤟
ramp-signal-3 = 󰤢
ramp-signal-4 = 󰤥
ramp-signal-5 = 󰤨
ramp-signal-foreground = ${colors.rosewater}


[settings]
screenchange-reload = true
pseudo-transparency = true


