[colors]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #1a1b26
foreground = #bbc2cf
foreground-alt =#24283b 



red = #F7768E

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
